title = "luizdepra"

theme = "coder"

languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

paginate = 20
canonifyURLs = true

enableEmoji = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params]
author = "Luiz de Prá"
avatarURL = "images/avatar.jpg"
images = ["images/og_cover.png"]

dateFormat = "2006-01-02"

colorScheme = "auto"

customCSS = ["css/custom.css", "css/syntax.css"]

[params.goatCounter]
code = "luizdepra"

[params.utterances]
repo = "luizdepra/luizdepra.dev"
issueTerm = "pathname"
theme = "github-dark"

[languages.en]
languageName = ":uk:"

[languages.en.params]
description = "Luiz de Prá's personal website and blog"
keywords = "blog,developer,personal,software,python,c++,go,rust"
info = "Software Engineer and Game Developer"

[[languages.en.params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/luizdepra/"

[[languages.en.params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 2
url = "https://twitter.com/luizdepra/"

[[languages.en.params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/luizdepra/"

[[languages.en.params.social]]
name = "RSS"
icon = "fa fa-rss-square fa-2x"
weight = 4
url = "/en/index.xml"

[[languages.en.menu.main]]
name = "Now"
weight = 1
url = "now/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Uses"
weight = 3
url = "uses/"

[[languages.en.menu.main]]
name = "About"
weight = 4
url = "about/"

[languages.pt-br]
languageName = ":brazil:"

[languages.pt-br.params]
description = "Site pessoal e blog de Luiz de Prá"
keywords = "blog,desenvolvedor,pessoal,software,python,c++,go,rust"
info = "Desenvolvedor de Software e Jogos"

[[languages.pt-br.params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/luizdepra/"

[[languages.pt-br.params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 2
url = "https://twitter.com/luizdepra/"

[[languages.pt-br.params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/luizdepra/"

[[languages.pt-br.params.social]]
name = "RSS"
icon = "fa fa-rss-square fa-2x"
weight = 4
url = "/pt-br/index.xml"

[[languages.pt-br.menu.main]]
name = "Agora"
weight = 1
url = "agora/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Usos"
weight = 3
url = "usos/"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 4
url = "sobre/"
